name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-setuptools python3-pip python3-opencv build-essential git zip unzip default-jdk

    - name: Install Buildozer & dependencies
      run: |
        pip install --upgrade pip setuptools
        pip install cython==0.29.36
        pip install buildozer
        sudo apt-get install -y libssl-dev libffi-dev libsqlite3-dev zlib1g-dev

    - name: Build APK with Buildozer
      run: |
        buildozer -v android debug

    - name: Archive APK
      uses: actions/upload-artifact@v4
      with:
        name: faceapp-apk
        path: bin/*.apk
